[install]
# Use exact versions for dependencies
exact = true

[install.scopes]
# Configure any scoped registries if needed

[test]
# Test configuration
preload = ["./__tests__/setup.ts"]

[run]
# Run configuration
bun = true 